### ISSUE TITLE
error: 'regparm' is not valid on this platform

### ISSUE THREAD

**Issue by Dtristone** [MPSLab-ASU/CCF-20.04#4]
Hello, I'm trying to use your tool to map programs onto cgra, but I meet some problems when call the "cgracc":

> In file included from /home/ccf/CCF-20.04-main/scripts/CGRALib/cgra.c:3:
> In file included from /home/ccf/CCF-20.04-main/scripts/CGRALib/cgra.h:7:
> /usr/include/pthread.h:657:6: error: 'regparm' is not valid on this platform
>      __cleanup_fct_attribute;
>      ^~~~~~~~~~~~~~~~~~~~~~~
> /usr/include/bits/pthreadtypes-arch.h:52:50: note: expanded from macro '__cleanup_fct_attribute'
> #define __cleanup_fct_attribute __attribute__ ((__regparm__ (1)))
>                                                  ^            ~
> In file included from /home/ccf/CCF-20.04-main/scripts/CGRALib/cgra.c:3:
> In file included from /home/ccf/CCF-20.04-main/scripts/CGRALib/cgra.h:7:
> /usr/include/pthread.h:669:3: error: 'regparm' is not valid on this platform
>   __cleanup_fct_attribute;
>   ^~~~~~~~~~~~~~~~~~~~~~~
> /usr/include/bits/pthreadtypes-arch.h:52:50: note: expanded from macro '__cleanup_fct_attribute'
> #define __cleanup_fct_attribute __attribute__ ((__regparm__ (1)))
>                                                  ^            ~
> In file included from /home/ccf/CCF-20.04-main/scripts/CGRALib/cgra.c:3:
> In file included from /home/ccf/CCF-20.04-main/scripts/CGRALib/cgra.h:7:
> /usr/include/pthread.h:710:6: error: 'regparm' is not valid on this platform
>      __cleanup_fct_attribute __attribute__ ((__noreturn__))
>      ^~~~~~~~~~~~~~~~~~~~~~~
> /usr/include/bits/pthreadtypes-arch.h:52:50: note: expanded from macro '__cleanup_fct_attribute'
> #define __cleanup_fct_attribute __attribute__ ((__regparm__ (1)))
>                                                  ^            ~
> 3 errors generated.

I build this tool on ubunut2004 using docker. The versions of openssl and cmake are the required ones.  Things go fine when I run the "install.h". I have no idea why the problem occurs . Is it because that this tool is still under developing and not avaliable?
(sad ：(

**Comment by shibizhao** [comment]
You may have to install cross-compiling environment of ARM in your docker. I have solved this problem but met another one.
Hope to be helpful to you!

**Comment by Dtristone** [comment]
> You may have to install cross-compiling environment of ARM in your docker. I have solved this problem but met another one. Hope to be helpful to you!

I installed the environment of ARM after building the openssl. Now mapping works fine. This is enough for me. Think you!
